SELECT COUNT(*) 전체직원수,
       COUNT(DECODE(EXTRACT(YEAR FROM HIRE_DATE), '2001', 1)) "2001년 입사직원수",
       COUNT(DECODE(EXTRACT(YEAR FROM HIRE_DATE), '2002', 1)) "2002년 입사직원수",
       COUNT(DECODE(EXTRACT(YEAR FROM HIRE_DATE), '2003', 1)) "2003년 입사직원수",
       COUNT(DECODE(EXTRACT(YEAR FROM HIRE_DATE), '2004', 1)) "2004년 입사직원수"
FROM EMPLOYEE;

SELECT COUNT(*) 전체직원수,
       COUNT(CASE WHEN TO_CHAR(HIRE_DATE, 'RRRR') = '2001' THEN 1 END) "2001년 입사직원수"
FROM EMPLOYEE;

SELECT COUNT(*) 전체직원수,
       COUNT(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE) = '2001' THEN 1 END) "2001년 입사직원수"
FROM EMPLOYEE;

SELECT COUNT(*) 전체직원수,
        COUNT(DECODE(TO_CHAR(HIRE_DATE, 'RRRR'), '2001', 1)) "2001년 입사직원수"
FROM EMPLOYEE;
