-- 7.
SELECT CLASS_NAME, DEPARTMENT_NAME
  FROM TB_CLASS
  JOIN TB_DEPARTMENT USING(DEPARTMENT_NO); 
  
-- 8.
SELECT CLASS_NAME, PROFESSOR_NAME
  FROM TB_CLASS
  JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
  JOIN TB_PROFESSOR USING(PROFESSOR_NO); 
  
-- 11.
SELECT DEPARTMENT_NAME, STUDENT_NAME, PROFESSOR_NAME
  FROM TB_STUDENT
  JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
  JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
 WHERE STUDENT_NO = 'A313047'; 

-- 13.
SELECT CLASS_NAME, DEPARTMENT_NAME
  FROM TB_CLASS
  LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
  JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
 WHERE CATEGORY = '예체능'
   AND PROFESSOR_NO IS NULL;

-- 17.
SELECT STUDENT_NAME, STUDENT_ADDRESS
  FROM TB_STUDENT
 WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                          FROM TB_STUDENT
                         WHERE STUDENT_NAME = '최경희'); 

-- 18.
SELECT STUDENT_NO, STUDENT_NAME
  FROM (SELECT STUDENT_NO, STUDENT_NAME, AVG(POINT)
          FROM TB_GRADE
          JOIN TB_STUDENT USING(STUDENT_NO)
         WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                                  FROM TB_DEPARTMENT
                                 WHERE DEPARTMENT_NAME = '국어국문학과'
                                )
         GROUP BY STUDENT_NO, STUDENT_NAME
         ORDER BY AVG(POINT) DESC
         )
-- WHERE ROWNUM = 1; 
FETCH FIRST 1 ROWS ONLY;  
-- FETCH FIRST n ROWS ONLY;    -- 12C이상 버전에서 사용
 
-- MAX()
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NO, STUDENT_NAME
HAVING AVG(POINT) = (SELECT MAX(AVG(POINT))
                        FROM TB_GRADE
                        JOIN TB_STUDENT USING(STUDENT_NO)
                        JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
                       WHERE DEPARTMENT_NAME = '국어국문학과'
                       GROUP BY STUDENT_NO);
                        


