-- 3.
create table tb_국어국문학과
as select student_no
        , student_name
        , EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 2), 'RRRR')) 출생년도
        , NVL(PROFESSOR_NAME, '지도교수 없음') PROFESSOR_NAME
    FROM TB_STUDENT S
LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
LEFT JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과';


SELECT CLASS_NO, CLASS_NAME
  FROM TB_CLASS
 WHERE CLASS_NAME = '피부생리학'; -- C3843900
 
SELECT STUDENT_NO, STUDENT_NAME
  FROM TB_STUDENT
 WHERE STUDENT_NAME = '김명훈'; 
 
 SELECT DEPARTMENT_NAME
  FROM TB_DEPARTMENT
 WHERE DEPARTMENT_NAME = '의학과';
 
UPDATE TB_GRADE
SET POINT = 3.5
WHERE STUDENT_NO = (SELECT STUDENT_NO
                      FROM TB_STUDENT
                      JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
                     WHERE STUDENT_NAME = '김명훈'
                       AND DEPARTMENT_NAME = '의학과')
  AND CLASS_NO = (SELECT CLASS_NO
                    FROM TB_CLASS
                   WHERE CLASS_NAME = '피부생리학');
-- 확인시                   
SELECT CLASS_NO, STUDENT_NO,POINT
  FROM TB_GRADE
 WHERE CLASS_NO = 'C3843900';
